version: 1.0.{build}
image: Visual Studio 2022

init:
  - git config --global core.autocrlf true

# Указываем, какие версии Node.js использовать
environment:
  matrix:
    - nodejs_version: "18"

install:
  # Устанавливаем Node.js
  - ps: Install-Product node $env:nodejs_version
  # Устанавливаем зависимости
  - yarn install

build_script:
  - yarn build  # Сборка проекта (создаст папку dist)

artifacts:
  - path: dist
    name: build

deploy_script:
  - ps: |
      git config --global user.email "your-email@example.com"
      git config --global user.name "your-github-username"
      git remote set-url origin https://your-github-token@github.com/your-github-username/your-repository.git
      yarn build
      npx gh-pages -d dist
